#pragma once

// Aggregated includes for all ES2025 modules.

#include "spectre/es2025/modules/array_buffer_module.h"
#include "spectre/es2025/modules/array_module.h"
#include "spectre/es2025/modules/async_function_module.h"
#include "spectre/es2025/modules/async_iterator_module.h"
#include "spectre/es2025/modules/atomics_module.h"
#include "spectre/es2025/modules/bigint_module.h"
#include "spectre/es2025/modules/boolean_module.h"
#include "spectre/es2025/modules/data_view_module.h"
#include "spectre/es2025/modules/date_module.h"
#include "spectre/es2025/modules/error_module.h"
#include "spectre/es2025/modules/finalization_registry_module.h"
#include "spectre/es2025/modules/function_module.h"
#include "spectre/es2025/modules/generator_module.h"
#include "spectre/es2025/modules/global_module.h"
#include "spectre/es2025/modules/intl_module.h"
#include "spectre/es2025/modules/iterator_module.h"
#include "spectre/es2025/modules/json_module.h"
#include "spectre/es2025/modules/map_module.h"
#include "spectre/es2025/modules/math_module.h"
#include "spectre/es2025/modules/module_loader_module.h"
#include "spectre/es2025/modules/number_module.h"
#include "spectre/es2025/modules/object_module.h"
#include "spectre/es2025/modules/promise_module.h"
#include "spectre/es2025/modules/proxy_module.h"
#include "spectre/es2025/modules/reflect_module.h"
#include "spectre/es2025/modules/regexp_module.h"
#include "spectre/es2025/modules/set_module.h"
#include "spectre/es2025/modules/shadow_realm_module.h"
#include "spectre/es2025/modules/shared_array_buffer_module.h"
#include "spectre/es2025/modules/string_module.h"
#include "spectre/es2025/modules/structured_clone_module.h"
#include "spectre/es2025/modules/symbol_module.h"
#include "spectre/es2025/modules/temporal_module.h"
#include "spectre/es2025/modules/typed_array_module.h"
#include "spectre/es2025/modules/weak_map_module.h"
#include "spectre/es2025/modules/weak_ref_module.h"
#include "spectre/es2025/modules/weak_set_module.h"

